/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package info.loenwind.compare;

import org.junit.Test;

import info.loenwind.compare.Main;

import static org.junit.Assert.assertTrue;

public class LibraryTest {
  @Test
  public void testSomeLibraryMethod() {
    Main classUnderTest = new Main();
    assertTrue("someLibraryMethod should return 'true'", true);
  }
}
